version: '3.8'

networks:
  kong-net:
    name: kong-net
    driver: bridge

services:
  kong:
    image: kong:3.1.1-alpine
    container_name: kong
    hostname: kong
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - kong-net
    volumes:
      - ./marketplaces-tools/config:/opt/kong
    env_file:
      - ./docker-env/production.env
    ports:
      - "1001:8000"
      - "1002:8443"
      - "1003:8001"
      - "1004:8444"

  konga:
    image: pantsel/konga
    container_name: konga
    hostname: konga
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - kong-net
    volumes:
      - ./marketplaces-tools/config/konga/user.js:/app/user_seed.js:ro
      - ./marketplaces-tools/config/konga/node.js:/app/node_seed.js:ro
    env_file:
      - ./docker-env/production.env
    ports:
      - "1337:1337"

  go-api:
    build:
      context: .
      dockerfile: marketplaceDockerfile
    image: go-api
    hostname: go-api
    container_name: go-api
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - kong-net
    expose:
      - "30000"
