version: '3.8'

networks:
  kong-net:
    name: kong-net
    driver: bridge

services:
  kong-migrations:
    image: kong:3.1.1-alpine
    container_name: kong-migrations
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: db-postgresql-sgp1-85109-do-user-3075863-0.b.db.ondigitalocean.com
      KONG_PG_PORT: 25060
      KONG_PG_USER: doadmin
      KONG_PG_SSL: 'on'
      KONG_PG_PASSWORD: AVNS_dK0ZYNLf8CZp1mnD0if
      KONG_CASSANDRA_CONTACT_POINTS: kong
    entrypoint: sh -c "kong migrations bootstrap --vv"
    networks:
      - kong-net
  konga-prepare:
    image: pantsel/konga
    container_name: konga-prepare
    command: "-c prepare -a postgres -u postgresql://doadmin:AVNS_dK0ZYNLf8CZp1mnD0if@db-postgresql-sgp1-85109-do-user-3075863-0.b.db.ondigitalocean.com:25060/konga?ssl=true"
    networks:
      - kong-net
    restart: on-failure
