version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=marketplaces
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./db:/data/db

volumes:
  db:
    driver: local
