_format_version: "1.1"

consumers:
- custom_id: tuannguyen
  username: tuannguyen
jwt_secrets:
- consumer: tuannguyen
  algorithm: HS256
  key: 0pOR32s8ycLbUdVu7uLRP2HhIDP6n2eE
  secret: pyk8mCpScq6YmndVxEnzdYgLtg5H7E7Y

plugins:
- name: jwt
  enabled: yes
  service: default-service
  config: 
    header_names: ["Authorization"]    
    uri_param_names: 
    key_claim_name: iss
    run_on_preflight: true     

upstreams:
- name: default-upstream
  hash_on: none
  algorithm: round-robin
  tags: 
  hash_fallback: none
  hash_on_cookie_path: "/"
  healthchecks:
    active:
      unhealthy:
        http_statuses:
        - 429
        - 404
        - 500
        - 501
        - 502
        - 503
        - 504
        - 505
        tcp_failures: 0
        timeouts: 0
        http_failures: 0
        interval: 0
      type: https
      http_path: "/"
      timeout: 1
      healthy:
        successes: 0
        interval: 0
        http_statuses:
        - 200
        - 302
      https_verify_certificate: true
      concurrency: 10
    passive:
      unhealthy:
        http_failures: 0
        http_statuses:
        - 429
        - 500
        - 503
        tcp_failures: 0
        timeouts: 0
      healthy:
        http_statuses:
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 206
        - 207
        - 208
        - 226
        - 300
        - 301
        - 302
        - 303
        - 304
        - 305
        - 306
        - 307
        - 308
        successes: 0
      type: https
  slots: 200
  targets:
    - target: reqres.in:443
      weight: 200

services:
- name: default-service
  host: default-upstream
  connect_timeout: 60000
  protocol: https
  read_timeout: 60000
  port: 443
  path: "/"
  retries: 5
  write_timeout: 60000  
  routes:
    - name: default-route
      methods: 
      - GET        
      paths:
        - /api/users
      protocols:
      - http
      - https
      regex_priority: 0
      strip_path: false
      preserve_host: false 